routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminNewsController;
use App\Http\Controllers\Admin\AuthController;
use Illuminate\Support\Facades\Route;

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('login_process', [AuthController::class, 'login'])->name('login_process');

Route::middleware('auth:admin')->group(function () {
    Route::resource('news', AdminNewsController::class);
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use \App\Http\Controllers\OneCategoryController;
use App\Http\Controllers\OneNewsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/category/{id}', [OneCategoryController::class, 'getOneCategory'])->name('getOneCategory');
Route::get('news/{id}', [OneNewsController::class, 'getOneNews'])->name('getOneNews');

resources/views/admin/index.blade.php
@extends('../templates.main')

@section('content')
    <a href="{{ route('admin.news.create') }}" class="transition-button">
        <span class="transition-button__text">Добавить</span>
    </a>
    <section class="news">
        @foreach($news as $item)
            <div class="block-news">
                <a href="{{ route('admin.news.show', $item->id) }}">
                    <h2>{{$item->title}}</h2>
                    <p> {{$item->description}}</p>
                </a>
            </div>
        @endforeach
        {{ $news->links() }}
    </section>
@endsection

resources/views/admin/login.blade.php
@extends('../templates.main')

@section('content')
    <div class="h-screen bg-white flex flex-col space-y-10 justify-center items-center">
        <div class="bg-white w-96 shadow-xl rounded p-5">
            <h1 class="text-3xl font-medium">Вход</h1>

            <form method="POST" action="{{ route("admin.login_process") }}" class="space-y-5 mt-5">
                @csrf

                <input name="email" type="text"
                       class="w-full h-12 border border-gray-800 rounded px-3 @error('email') border-red-500 @enderror"
                       placeholder="Email"/>

                @error('email')
                <p class="text-red-500">{{ $message }}</p>
                @enderror

                <input name="password" type="password"
                       class="w-full h-12 border border-gray-800 rounded px-3 @error('password') border-red-500 @enderror"
                       placeholder="Пароль"/>

                @error('password')
                <p class="text-red-500">{{ $message }}</p>
                @enderror

                <button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium">
                    Войти
                </button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/newNews.blade.php
@extends('../templates.main')

@section('content')



    <div class="mt-8">
        <form class="space-y-5 mt-5" method="POST"
              action="{{ isset($news) ? route("admin.news.update", $news->id) : route("admin.news.store") }}">
            @csrf

            @if(isset($news))
                @method('PUT')
            @endif

            @if(is_int($category))
                <input hidden type="checkbox" name="category_id" value="{{$category}}" checked>
            @else
                @foreach($category as $item)
                    <label>
                        <input type="radio" name="category_id" value="{{$item->id}}">
                        {{$item->title}}
                    </label>
                @endforeach
            @endif


            <input name="title" type="text"
                   class="w-full h-12 border border-gray-800 rounded px-3 @error('title') border-red-500 @enderror"
                   placeholder="Название" value="{{ $news->title ?? '' }}"/>

            @error('title')
            <p class="text-red-500">{{ $message }}</p>
            @enderror

            <input name="description" type="text"
                   class="w-full h-12 border border-gray-800 rounded px-3 @error('description') border-red-500 @enderror"
                   placeholder="Описание" value="{{ $news->description ?? '' }}"/>

            @error('description')
            <p class="text-red-500">{{ $message }}</p>
            @enderror

            <input name="news_body" type="text"
                   class="w-full h-12 border border-gray-800 rounded px-3 @error('news_body') border-red-500 @enderror"
                   placeholder="Текст" value="{{ $news->news_body ?? '' }}"/>

            @error('news_body')
            <p class="text-red-500">{{ $message }}</p>
            @enderror

{{--            <input name="slug" type="text"--}}
{{--                   class="w-full h-12 border border-gray-800 rounded px-3 @error('slug') border-red-500 @enderror"--}}
{{--                   placeholder="Псевдоним для новости" value="{{ $news->slug ?? '' }}"/>--}}

{{--            @error('description')--}}
{{--            <p class="text-red-500">{{ $message }}</p>--}}
{{--            @enderror--}}

            <button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium">
                Сохранить
            </button>
        </form>
    </div>

    <div class="transition">
        <a href="{{$route}}" class="transition-button">
            <span class="transition-button__text">{{$title_button}}</span>
        </a>
    </div>
@endsection

resources/views/admin/news.blade.php
@extends('templates.main')

@section('content')

    <section class="news">
        <div class="block-news">
            <h2>{{$news->title}}</h2>
            <p> {{$news->description}}</p>
            <p class="block-news__text">{{$news->news_body}}</p>
        </div>
        <div class="action">
            <a href="{{ route('admin.news.edit', $news->id) }}" class="transition-button">
                <span class="transition-button__text">Редактировать</span>
            </a>

            <form action="{{ route('admin.news.destroy', $news->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="transition-button">Удалить</button>
            </form>

        </div>

        <div class="transition">
            <a href="{{route('admin.news.index')}}" class="transition-button">
                <span class="transition-button__text">Вернуться назад</span>
            </a>
        </div>
    </section>
@endsection